CREATE DATABASE Empresa;
USE Empresa;

-- CREANDO TABLAS --

CREATE TABLE Departamentos (
    COD_DEP INT PRIMARY KEY,
    NOMBRE_DEP VARCHAR(20),
    PRESUPUESTO INT
);

CREATE TABLE Empleados (
    DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE_EMPLEADO VARCHAR (20),
    APELLIDOS VARCHAR (15),
    CODIGO_DEP INT NOT NULL
);

ALTER TABLE Empleados ADD FOREIGN KEY CODIGO_DEP REFERENCES Departamentos(COD_DEP);

INSERT INTO Departamentos (COD_DEP, NOMBRE_DEP, PRESUPUESTO) VALUES (20,"Contabilidad", 10000);
INSERT INTO Departamentos (COD_DEP, NOMBRE_DEP, PRESUPUESTO) VALUES (40,"Ventas", 25000);
INSERT INTO Departamentos (COD_DEP, NOMBRE_DEP, PRESUPUESTO) VALUES (20,"Compras", 20000);
INSERT INTO Departamentos (COD_DEP, NOMBRE_DEP, PRESUPUESTO) VALUES (20,"Proyectos", 50000);
INSERT INTO Departamentos (COD_DEP, NOMBRE_DEP, PRESUPUESTO) VALUES (20,"Direccion", 70000);

INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("43886958K","Ayose", "Santana", 60);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("75896398J","Airam", "Cabrera", 40);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("23568984A","Ainara", "Betancor", 20);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("45897868W","Guillermina", "Brito", 20);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("23568948B","Eduardo", "Marrero", 90);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("15789638D","Tomas", "Betancor", 70);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("42669898G","Lucia", "Cruz", 70);
INSERT INTO Empleados (DNI, NOMBRE_EMPLEADO, APELLIDOS, COD_DEP) VALUES ("75899687D","Juan Jesús", "Santana", 70);




-- CONSULTAS --

1. SELECT APELLIDOS FROM Empleados;
2. SELECT DISTINCT APELLIDOS FROM Empleados;
3. SELECT * FROM Empleados WHERE APELLIDOS LIKE = "Betancor";
4. SELECT * FROM Empleados WHERE APELLIDOS LIKE = "Betancor"

8. SELECT SUM(DEPARTAMENTOS.PRESUPUESTO);
9. SELECT COD_DEP, COUNT(*) FROM Empleados GROUP BY COD_DEP;
10. SELECT * FROM Empleados JOIN Departamentos ON Empleados.CODIGO_DEP; 
11. SELECT (NOMBRE_EMPLEADO, APELLIDOS) FROM Empleados, Departamentos WHERE CODIGO_DEP = COD_DEP AND PRESUPUESTO > 40000;
-- SELECT Empleados.NOMBRE_EMPLEADO Empleados.APELLIDOS FROM Empleados, Departamentos WHERE Empleados.CODIGO_DEP = Departamentos.COD_DEP AND Departamentos.PRESUPUESTO > 40000;-- 
12. SELECT * FROM Departamentos WHERE PRESUPUESTO > (SELECT AVG(PRESUPUESTO) FROM Departamentos);
13. SELECT NOMBRE_DEP FROM Departamentos WHERE COD_DEP(SELECT COUNT (DNI), CODIGO_DEP FROM Empleados GROUP BY CODIGO_DEP HAVING COUNT(DNI) > 2) AS TABLA_RESULT WHERE Departamentos.CODIGO_DEP = TABLA_RESULT;
 -- "HAVING es como un WHERE" YA QUE FORMA PARTE DE LA MISMA CONDICIÓN QUE COUNT --