CREATE DATABASE Startrekfans;
USE Startrekfans;

-- CREANDO TABLAS --

CREATE TABLE Actores(
    COD_ACTOR int PRIMARY KEY,
    NOM_ACTOR varchar(15),
    FECHA date,
    NACIONALIDAD varchar
);

CREATE TABLE Personajes(
    COD_PERSONAJE int,
    NOM_PERSONAJE varchar(15),
    RAZA varchar(10),
    GRADO varchar(10),
    COD_ACTOR int,
    COD_SUPERIOR int
);

CREATE TABLE Planetas(
    COD_PLANETA int PRIMARY KEY,
    GALAXIA varchar(18),
    NOM_PLANETA varchar(15)
);

CREATE TABLE Capitulos(
    TEMPORADA int,
    ORDEN int,
    TITULO varchar(15),
    FECHA date,
    PRIMARY KEY(TEMPORADA,ORDEN)
);

CREATE TABLE Peliculas(
    COD_PELICULA int PRIMARY KEY,
    T_PELICULA varchar(20),
    PERIODO date
    -- PERIODO HACE REFERENCIA AL AÑO --
);

CREATE TABLE PersonajesCapitulos(
    CODIGO_PERSONAJE int PRIMARY KEY,
    TEMPORADA int,
    ORDEN int,
);

CREATE TABLE PersonajesPeliculas(
    CODIGO_PERSONAJE int,
    CODIGO_PELICULA int,
    PRIMARY KEY(CODIGO_PERSONAJE,CODIGO_PELICULA)
);

CREATE TABLE Naves(
    COD_NAVE int PRIMARY KEY,
    N_TRIPULANTES int,
    NOM_NAVE varchar(15),
);

CREATE TABLE Visitas(
    CODIGO_NAVE int, 
    CODIGO_PLANETA int,
    TEMPORADA int,
    ORDEN int,
    PRIMARY KEY(TEMPORADA,ORDEN)
);

/**** CLAVES FORÁNEAS ****/
ALTER TABLE Personajes ADD FOREIGN KEY COD_ACTOR REFERENCES Actores(COD_ACTOR);
ALTER TABLE Personajes ADD FOREIGN KEY COD_SUPERIOR REFERENCES Personajes(COD_PERSONAJE);
ALTER TABLE PersonajesCapitulos ADD FOREIGN KEY TEMPORADA REFERENCES Capitulos();
ALTER TABLE PersonajesPeliculas ADD FOREIGN KEY CODIGO_PERSONAJE REFERENCES Personajes(COD_PERSONAJE);
ALTER TABLE PersonajesPeliculas ADD FOREIGN KEY CODIGO_PELICULA REFERENCES Peliculas(COD_PELICULA);
ALTER TABLE Visitas ADD FOREIGN KEY CODIGO_NAVE REFERENCES Naves(COD_NAVE);
ALTER TABLE Visitas ADD FOREIGN KEY CODIGO_PLANETA REFERENCES Planetas(COD_PLANETA);

/****** APARTADOS ******/
-- 1. MODIFICAR LAS CLAVES PRIMARIAS NUMÉRICAS --
ALTER TABLE Actores MODIFY COD_ACTOR int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Planetas MODIFY COD_PLANETA int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Actores MODIFY COD_ACTOR int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Capitulos MODIFY TEMPORADA int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Capitulos MODIFY ORDEN int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Peliculas MODIFY COD_PELICULA int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE PersonajesCapitulos MODIFY CODIGO_PERSONAJE int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE PersonajesPeliculas MODIFY CODIGO_PERSONAJE int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE PersonajesPeliculas MODIFY CODIGO_PELICULA int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Naves MODIFY COD_NAVE int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Visitas MODIFY TEMPORADA int AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Visitas MODIFY ORDEN int AUTO_INCREMENT PRIMARY KEY;

-- 2. MODIFICAR EL CAMPO GALAXIA DE LA TABLA PLANETAS --
ALTER TABLE Planetas MODIFY GALAXIA varchar ENUM('Vía Láctea','Andrómeda','Sombrero');

-- 3. DE LA TABLA PERSONAJES AÑADIR LOS DATOS CIUDAD, F_NACIMIENTO, PLANETA(FOREIGN_KEY), FULTICOMBABTE, MENTOR, FECHA_GRADO --
ALTER TABLE Personajes ADD CIUDAD varchar(50);
ALTER TABLE Personajes ADD F_NACIMIENTO date;
ALTER TABLE Personajes ADD FOREIGN KEY PLANETA int REFERENCES Planetas(COD_PLANETA);
ALTER TABLE Personajes ADD F_ULTI_COMBATE date;
ALTER TABLE Personajes ADD FECHA_GRADO date;

-- 4. CREAR NUEVA TABLA LANZADERAS CON LA SIGUIENTE INFORMACIÓN --
CREATE TABLE Lanzaderas (
    COD_NAVE int,
    NUMERO int,
    PERSONAJES int,
    PRIMARY KEY(COD_NAVE, NUMERO)
);

ALTER TABLE Lanzaderas ADD FOREIGN KEY COD_NAVE REFERENCES Naves(COD_NAVE);









